server:
  port: 0

spring:
  application:
    name: restaurant-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

logging:
  level:
    com.example.restaurant_service: DEBUG
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#greeting:
#  message: Welcome to the Simple E-Commerce.
management:
  endpoint:
    web:
      exposure:
        include: refresh,health,beans,info,metrics,prometheus

