server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
        - id: Restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant-service/**
        - id: Review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
